import React from 'react';
import './Ai_page.css';
import Ai_card from '../../src/components/Ai_card/Ai_card';
import c1 from "../assets/client1.jpeg";
import c2 from "../assets/client2.jpeg";
import c3 from "../assets/client3.jpeg";
import c4 from "../assets/client4.jpeg";
import c5 from "../assets/client5.jpeg";
import raveena from '../assets/Raveena.jpeg'
import manthan from '../assets/Manthan.jpeg'
import sanskar from '../assets/Sanskar.jpeg'

import { useState } from 'react';
import { FaHeartbeat, FaUtensils, FaShoppingCart, FaCarBattery, FaPlane, FaMusic, FaUsers, FaGlobe, FaHome, FaLeaf, FaGasPump, FaCar, FaUmbrella, FaIndustry, FaGraduationCap, FaNetworkWired, FaBoxes, FaTractor,FaPython,  FaDatabase, FaRobot, FaServer, FaBox, FaProjectDiagram, FaChartLine, FaTable, FaChartBar, FaBrain, FaCloud, FaAws, FaCode, FaTools, FaInfinity, FaBook, FaCubes  } from "react-icons/fa";
// import { FaPython, FaDatabase, FaRobot, FaServer, FaBox, FaProjectDiagram, FaChartLine, FaTable, FaChartBar, FaBrain, FaCloud, FaAws, FaCode, FaTools, FaInfinity, FaBook, FaCubes } from "react-icons/fa";




const ai_cardData = [
  { icon: <FaHeartbeat />, title: "Healthcare" },
  { icon: <FaChartLine />, title: "Finance" },
  { icon: <FaUtensils />, title: "Restaurant" },
  { icon: <FaShoppingCart />, title: "eCommerce" },
  { icon: <FaCarBattery />, title: "Electric Vehicle (EV)" },
  { icon: <FaCloud />, title: "SaaS" },
  { icon: <FaPlane />, title: "Travel" },
  { icon: <FaMusic />, title: "Entertainment" },
  { icon: <FaUsers />, title: "On-Demand" },
  { icon: <FaGlobe />, title: "Social Media" },
  { icon: <FaBoxes />, title: "Logistics" },
  { icon: <FaGraduationCap />, title: "Education" },
  { icon: <FaHome />, title: "Real Estate" },
  { icon: <FaLeaf />, title: "Aviation" },
  { icon: <FaNetworkWired />, title: "Telecom" },
  { icon: <FaTractor />, title: "Agriculture" },
  { icon: <FaGasPump />, title: "Oil and Gas" },
  { icon: <FaCar />, title: "Automotive" },
  { icon: <FaUmbrella />, title: "Insurance" },
  { icon: <FaIndustry />, title: "Manufacturing" },
]; 


const techStack = [
  { icon: <FaPython />, title: "Python" },
  { icon: <FaDatabase />, title: "Big Data" },
  { icon: <FaRobot />, title: "Machine Learning" },
  { icon: <FaServer />, title: "ETL" },
  { icon: <FaBox />, title: "Databricks" },
  { icon: <FaProjectDiagram />, title: "OpenCV" },
  { icon: <FaChartLine />, title: "Scikit-learn" },
  { icon: <FaTable />, title: "Pandas" },
  { icon: <FaChartBar />, title: "Tableau" },
  { icon: <FaBrain />, title: "Tensorflow" },
  { icon: <FaChartBar />, title: "Grafana" },
  { icon: <FaCloud />, title: "Azure" },
  { icon: <FaAws />, title: "AWS" },
  { icon: <FaCode />, title: "API" },
  { icon: <FaTools />, title: "DevOps" },
  { icon: <FaInfinity />, title: "Oracle" },
  { icon: <FaBook />, title: "Jupyter" },
  { icon: <FaCubes />, title: "Kubernetes" },
];


const caseStudies = [
  {
    statement: "Discovery of Profits not recognised in ERP",

    problem: {
      heading: "Problem ",
      description: " XYZ Ltd is into business of custom injection molding of plastic items.The company has recently implemented a new ERP system and as per the financial statements generated by the new system, Substantial loss and overall negative net-worth was observed",
    },
    solution: {
      heading: "Solution ",
      description: "Favourable variance (profit) arising due to high standard costs as compared to actual costs which was accumulated in WIP account were transferred to respective accounts (i.e., labor cost, other production cost) resulting in reduction of overall cost of production. An automated process was created for transfer of variance to respective accounts.",
    },
    results: {
      heading: "Results ",
      description: "Profitability was reinstated correctly in P&L account for the period ending on 31st March, 2019 from a loss amounting to Rs. 1 crore to actual profit of Rs. 5 Crore.",
    },
  },
  {
    statement: "Efficient production planning & inventory management",

    problem: {
      heading: "Problem 2",
      description: "EFG Ltd is into business of manufacturing automobile ancillary spare parts. The company did not maintain color-wise stock of assembly parts and had no record of color-wise production of parts. Production plan was made on the basis of finished goods required for sales, ignoring the stock available of assembly parts.",
    },
    solution: {
      heading: "Solution 2",
      description: "Color-wise stock was recorded in the current ERP system post physical stock taking. Color-wise BOM (Bill of Material) masters were created in the system, enabling plant managers to monitor the closing stock of assembly parts and perform efficient production planning.",
    },
    results: {
      heading: "Results 2",
      description: "Reduced inventory levels of assembly parts were achieved by avoiding substantial variation in available stock across assembly parts required for each unit of finished product. This led to a reduction in annual inventory carrying cost of Rs. 5,00,000.",
    },
  },
  {
    statement: "Increase Sales without Increase in Cost",

    problem: {
      heading: "Problem 3",
      description: "A home décor products & upholstery merchandise company was struggling with retail sales due to lack of product understanding among consumers.A catalogue was need of the hour, but production cost of a catalogue with fabric samples ranges from ₹600-4000.",
    },
    solution: {
      heading: "Solution 3",
      description: "Our analysis helped in prioritising key demand areas of the catalog based on product-wise, region-wise analysis of sales data.The company realised higher demand for plain curtains in areas of tourist interest and embroidered curtains in high standard of living areas.",
    },
    results: {
      heading: "Results 3",
      description: "Net increase in sales across regions of ₹15,00,000 was achieved without any change in total cost involved in the preparation and distribution of product catalogues.",
    },
  },
  {
    statement: "Improvements in Operational Efficiencies",

    problem: {
      heading: "Problem 4",
      description: "ABC Ltd, a manufacturer of plastic furniture, faced challenges in monitoring daily production activities at both the plant and head office level. The reliance on monthly Excel-based MIS, due to the absence of a dedicated production module, led to inefficiencies.Additionally, the MIS format failed to provide accurate insights into product cycle time and overall efficiency across the factory.",
    },
    solution: {
      heading: "Solution 4",
      description: "To address these issues, the data collection process was revised to track material rejection during production and hourly production rates.Furthermore, interactive and visually intuitive dashboards were developed, enabling plant managers and executives to monitor real-time data, including cycle time, machine utilization, machine downtime, and production rejection analysis.",
    },
    results: {
      heading: "Results 4",
      description: "The implementation of these solutions enhanced monitoring capabilities, reducing product cycle time and improving machine utilization and production output.Additionally, production costs decreased due to better planning and optimized use of available machine hours.",
    },
  },
];




const Ai_page = () => {

const clients = [c1, c2, c3, c4, c5];

const [openIndex, setOpenIndex] = useState(null);

const questions = [
  { id: 1, title: "Comprehensive and Tailored AI Services", content: "We offer AI services that are customized to meet your specific business needs." },
  { id: 2, title: "Compliance-First Approach", content: "Our AI solutions prioritize compliance with industry standards and regulations." },
  { id: 3, title: "Innovation-Inclusive Culture", content: "We foster an environment where innovation drives AI advancements." },
  { id: 4, title: "Proven Track Record", content: "Our AI implementations have consistently delivered impactful results." },
];

const toggleDropdown = (index) => {
  setOpenIndex(openIndex === index ? null : index);
};

const [currentIndex, setCurrentIndex] = useState(0);

  const nextSlide = () => {
    setCurrentIndex((prevIndex) =>
      prevIndex === caseStudies.length - 1 ? 0 : prevIndex + 1
    );
  };

  const prevSlide = () => {
    setCurrentIndex((prevIndex) =>
      prevIndex === 0 ? caseStudies.length - 1 : prevIndex - 1
    );
  };


  return (
    <div className='ai_container'>
      <div className="video_container">
      {/* <video autoPlay loop muted playsInline defaultmuted="true" className="bg_video">
  <source src= "/videos/Ai_bg.mp4" type="video/mp4" />
  Your browser does not support the video tag.
</video> */}
        <div className="video_overlay"></div>
        <div className="heading_tagline">
          <h1>Empowering Autonomous Growth <br /> with Time-Tested AI Services and Solutions</h1>
          <h3>
            Unlock new potential and upgrade existing business capabilities with AI services that streamline operations, <br />
            elevate customer experience, and drive innovation.
          </h3>
          <button className='cta_ai'>AI CTA</button>

          <div className="clients_showcase">
        <h2>Trusted by</h2>
        <div className="clients-grid">
          {clients.map((logo, index) => (
            <div key={index} className="client-logo">
              <img src={logo} alt={`Client ${index + 1}`} />
            </div>
          ))}
        </div>
      </div>
        </div>
      

      
      </div>




      <div className="scale_section">
        <h1>Scale Smarter with our Site of Artificial Intelligence Services and Solutions.</h1>
        <h3>Explore our comprehensive suite of AI services designed to drive profitable innovations and deliver tangible outcomes. From consulting to development and beyond, our extensive artificial intelligence services and solutions are tailored to meet unique business needs in any industry.</h3>
<br />
        <div className="applications_card">
          <h2>Business Applications</h2>
        <div className="services_box">

          
          <div className="services_given">
          <i className="fa-solid fa-robot"></i>
          Identification of AI-Driven Automation Opportunities

          </div>

          <div className="services_given">
          <i className="fa-solid fa-percent"></i>
          AI Governance and Compliance Strategies Creation

          </div>

          <div className="services_given">
          <i className="fa-solid fa-puzzle-piece"></i>
          AI Ethics and Responsible AI Frameworks Implementation

          </div>

          <div className="services_given">
          <i className="fa-solid fa-people-arrows"></i>
            Ethical andResponsible AI Framework Integration

          </div>

        </div>

        <br />
        <br />

        <h2>Our Offerings</h2>
        <p>Unlock the full creative potential of gen Al with our Generative Al  
your team to craft tailored roadmaps that seamlessly integrate ge  
impact use cases that drive innovation and efficiency.</p>
       
          
        </div>
      </div>



      <div className="faq-container">
      {/* Left Side Text Section */}
      <div className="faq-left">
        <h2>What Makes Our AI Services Ideal for You?</h2>
        <p>
          As a premium AI services company, we provide tailored AI solutions designed for your business needs.
          Our expertise ensures custom AI solutions that are strategically developed to deliver exceptional results.
        </p>
      </div>

      {/* Right Side Accordion Section */}
      <div className="faq-right">
        {questions.map((item, index) => (
          <div key={item.id} className="faq-item">
            <div className="faq-question" onClick={() => toggleDropdown(index)}>
              <span>{index + 1}/ {item.title}</span>
              <span className="arrow">{openIndex === index ? "▲" : "▶"}</span>
            </div>
            <div className={`faq-answer ${openIndex === index ? "open" : ""}`}>
              <p>{item.content}</p>
            </div>
          </div>
        ))}
      </div>
    </div>





    <div className="our_team_section">
      <h2>Meet Our Experts Members</h2>
      <div className="member">
        <div className="profile">
          <div className="img_person">
          <img src= {sanskar} alt="" />
          </div>
      
          <div className="intro">
          <h2>Sanskaar Dubey</h2>
          <p>Founder</p>

          </div>
          

        </div>
        <div className="about">
          <p>Sanskar Dubey is the founder of Step Consultancy, the parent company of Step Tech, a venture dedicated to building innovative, scalable, and business-centric technology solutions. With a vision to bridge the gap between businesses and digital transformation, Step Tech focuses on creating high-performance web and mobile applications, enterprise software, and AI-driven automation tools that drive efficiency and growth. </p>
        </div>

        
      </div>

      <div className="member">
        <div className="profile">
          <div className="img_person">
          <img src= {raveena} alt="" />
          </div>
      
          <div className="intro">
          <h2>Raveena Mishra </h2>
          <p>Project Associate | Tech Management Lead</p>

          </div>
          

        </div>
        <div className="about">
          <p>Raveena ensures the seamless execution of tech projects by streamlining processes, optimizing team collaboration, and maintaining on-time delivery. She plays a key role in project planning, resource management, and agile implementation while ensuring quality and efficiency throughout the development cycle.</p>
        </div>

        
      </div>


      <div className="member">
        <div className="profile"> 
          <div className="img_person">
          <img src= {manthan} alt="" />
          </div>
      
          <div className="intro">
          <h2>Manthan Jethwani</h2>
          <p>AI Engineer | AI Agents | AI Automation</p>
          


          </div>
          

        </div>
        <div className="about">
          <p>Manthan designs and builds intelligent AI solutions and Ai agents. He empowers businesses to reclaim valuable time by automating repetitive tasks, optimizing processes, reducing overhead, and accelerating growth.</p>
        </div>

        
      </div>

      

  


    </div>



    <div className="ai_cards">
      <h1>Industries We Empower and Transform with Our AI Services</h1>
      <p>
        Our AI services redefine businesses across industries by driving innovation, improving efficiency, and unlocking new growth opportunities. From healthcare, finance, retail, and real estate to travel and hospitality, we empower businesses to stay ahead of the competition with cutting-edge AI business solutions tailored to their unique needs.
      </p>
      <div className="grid-container">
        {ai_cardData.map((item, index) => (
          <Ai_card key={index} icon={item.icon} title={item.title} />
        ))}
      </div>
    </div>



    <div className="case_study_section">
      {/* Upper Section with Common Heading */}
      <div className="upper_case_study">
        <h2>Our Case Studies</h2>
        <p>Discover how we solved real-world problems with innovative solutions.</p>
      </div>

      {/* Bottom Section with Scrollable Case Studies */}
      <div className="bottom_case_study">
        <button className="arrow_ai btn_left" onClick={prevSlide}>&#8249;</button>

        <div className="case_study_wrapper">
          <br />
          <div className="case_study" style={{ transform: `translateX(-${currentIndex * 100}%)` }}>
            {caseStudies.map((study, index) => (
              <div className="case_study_item" key={index}>
                <div className="statement">
                
                {study.statement}

                </div>
               <div className="content_study">
               <div className="problem">
                  <h3>{study.problem.heading}</h3>
                  <p>{study.problem.description}</p>
                </div>
                <div className="solution">
                  <h3>{study.solution.heading}</h3>
                  <p>{study.solution.description}</p>
                </div>
                <div className="results">
                  <h3>{study.results.heading}</h3>
                  <p>{study.results.description}</p>
                </div>
               </div>
              </div>
            ))}
          </div>
        </div>

        <button className="arrow_ai btn_right" onClick={nextSlide}>&#8250;</button>
      </div>
    </div>



    <div className="ai_cards">
      <h1>AI Tech Stack Cluster We Use for Intelligent Model Development</h1>
      <p>
      Our custom AI solutions for businesses are meticulously crafted using an ideal technology stack tailored to meet every requirement of your business. From advanced machine learning frameworks to cloud-based platforms, we utilize the best tools to ensure scalable, stable, efficient, and innovative AI-oriented outcomes.
      </p>
      <div className="grid-container">
        {techStack.map((item, index) => (
          <Ai_card key={index} icon={item.icon} title={item.title} />
        ))}
      </div>
    </div>


  


    </div>
  );
};

export default Ai_page;
